import Platya from "@/components/Platya";
import { Metadata } from "next";





const meta = {
  title: 'Palettes',
  description: 'شملول هو موقع رائد يقدم مجموعة شاملة من الأدوات والموارد المبتكرة للمصممين والمبرمجين. يتيح الموقع للمستخدمين الوصول إلى مجموعة لونية واسعة تتيح لهم تحديد مظهر فريد لمشاريعهم باستخدام ألوان متنوعة وجذابة. بالإضافة إلى ذلك، يتميز الموقع بمكتبة ضخمة تحتوي على 1000 أيقونة إبداعية، مما يوفر للمستخدمين مصدرًا غنيًا لتحسين تجربة المستخدم في تصميماتهم',
}


export const metadata: Metadata = {
  title: meta.title,
  description: meta.description,
  twitter: {
    card:'summary_large_image'
  },
}




export default function Palettes() {
  return (
    <main>
      <head>
          {/* Facebook Meta Tags */}
          <meta property="og:url" content="https://shamlul.netlify.app" />
          <meta property="og:type" content="website" />
          <meta property="og:title" content="Shamlul" />
          <meta property="og:description" content='شملول هو موقع رائد يقدم مجموعة شاملة من الأدوات والموارد المبتكرة للمصممين والمبرمجين. يتيح الموقع للمستخدمين الوصول إلى مجموعة لونية واسعة تتيح لهم تحديد مظهر فريد لمشاريعهم باستخدام ألوان متنوعة وجذابة. بالإضافة إلى ذلك، يتميز الموقع بمكتبة ضخمة تحتوي على 1000 أيقونة إبداعية، مما يوفر للمستخدمين مصدرًا غنيًا لتحسين تجربة المستخدم في تصميماتهم' />
          <meta property="og:image" content="" />
          {/* Twitter Meta Tags */}
          <meta name="twitter:card" content="summary_large_image" />
          <meta property="twitter:domain" content="shamlul.netlify.app" />
          <meta property="twitter:url" content="https://shamlul.netlify.app" />
          <meta name="twitter:title" content="Shamlul" />
          <meta name="twitter:description" content="Generated by create next app" />
          <meta name="twitter:image" content="" />
      </head>
      <Platya />
    </main>
  )
}






