import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import './fonts.css'

//! VERCEL
import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from '@vercel/speed-insights/next';


// TODO: imports Components
import Navbar from '@/components/Navbar'
import AgreementForm from '@/components/AgreementForm'
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Shamlul',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <head>
        <Script
          async
          strategy='afterInteractive'
          src="https://www.googletagmanager.com/gtag/js?id=G-L7BN49S88M"
        />

        <Script id='google-analytics' strategy='afterInteractive'>
          {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
        
          gtag('config', 'G-L7BN49S88M');
        
      `}
        </Script>
        <meta name="google-site-verification" content="7nUh0NZyD1QQdy5Q2tnzD7mUk2-G14FAkLhhDWhkoR4" />
      </head>

      <body className={inter.className}>
        {/* <AgreementForm /> */}
        <Navbar />
        {children}
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  )
}
